(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.Data = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  // Generated by make-puzzles.js. 'start' is the scrambled grid, 'alts' are other words that count for a target,
  // 'par' is the fewest possible moves and 'solution' is one shortest path.
  const PUZZLES = [
    {
      "id": "slip-01",
      "words": [
        "BEAR",
        "ROAD",
        "DEAL",
        "LION"
      ],
      "alts": {
        "BEAR": [
          "BARE"
        ],
        "DEAL": [
          "LEAD"
        ],
        "LION": [
          "LOIN"
        ]
      },
      "start": "BDEDLEORLIAAROAN",
      "par": 5,
      "solution": [
        "c0-",
        "c3+",
        "c3+",
        "r0-",
        "c1-"
      ]
    },
    {
      "id": "slip-02",
      "words": [
        "PLAN",
        "SNOW",
        "TIME",
        "DOOR"
      ],
      "alts": {
        "SNOW": [
          "OWNS"
        ],
        "TIME": [
          "EMIT",
          "ITEM",
          "MITE"
        ],
        "DOOR": [
          "ODOR"
        ]
      },
      "start": "LONMEAIWSTORDNOP",
      "par": 4,
      "solution": [
        "c1-",
        "c3+",
        "r1-",
        "r0+"
      ]
    },
    {
      "id": "slip-03",
      "words": [
        "RAIN",
        "LAKE",
        "WIND",
        "SAND"
      ],
      "alts": {
        "LAKE": [
          "KALE"
        ]
      },
      "start": "NDSWDLINAKEIANRA",
      "par": 7,
      "solution": [
        "r0+",
        "r1-",
        "r2+",
        "c0+",
        "r3-",
        "r3-",
        "r0+"
      ]
    },
    {
      "id": "slip-04",
      "words": [
        "FIRE",
        "STAR",
        "BOAT",
        "MILK"
      ],
      "alts": {
        "FIRE": [
          "RIFE"
        ],
        "STAR": [
          "ARTS",
          "RATS",
          "TARS",
          "TSAR"
        ]
      },
      "start": "ARMIKFILBORESTAT",
      "par": 5,
      "solution": [
        "r0+",
        "r0+",
        "r1-",
        "c0+",
        "c1+"
      ]
    },
    {
      "id": "slip-05",
      "words": [
        "COOK",
        "BAKE",
        "SALT",
        "MEAL"
      ],
      "alts": {
        "BAKE": [
          "BEAK"
        ],
        "SALT": [
          "LAST",
          "SLAT"
        ],
        "MEAL": [
          "LAME",
          "MALE"
        ]
      },
      "start": "CKABSOKTMAOLAELE",
      "par": 4,
      "solution": [
        "c0+",
        "c2-",
        "r0+",
        "c3+"
      ]
    },
    {
      "id": "slip-06",
      "words": [
        "HOME",
        "ROOF",
        "WALL",
        "DESK"
      ],
      "alts": {},
      "start": "EAOLOWHSFEOKRLMD",
      "par": 7,
      "solution": [
        "r1-",
        "r2-",
        "c0-",
        "c2+",
        "r3+",
        "r1-",
        "c2+"
      ]
    },
    {
      "id": "slip-07",
      "words": [
        "JUMP",
        "RACE",
        "SWIM",
        "KICK"
      ],
      "alts": {
        "RACE": [
          "ACRE",
          "CARE"
        ]
      },
      "start": "MSAEKWUCPICKRJIM",
      "par": 5,
      "solution": [
        "c3-",
        "r0-",
        "c2+",
        "c1-",
        "r2-"
      ]
    },
    {
      "id": "slip-08",
      "words": [
        "GOLD",
        "COIN",
        "BANK",
        "RICH"
      ],
      "alts": {
        "COIN": [
          "ICON"
        ]
      },
      "start": "AOIBCONDGKIHCNRL",
      "par": 6,
      "solution": [
        "c1+",
        "r3-",
        "c2-",
        "r0+",
        "r3-",
        "c3+"
      ]
    },
    {
      "id": "slip-09",
      "words": [
        "TREE",
        "LEAF",
        "ROOT",
        "SEED"
      ],
      "alts": {
        "LEAF": [
          "FLEA"
        ]
      },
      "start": "DSATETEOLEOERREF",
      "par": 7,
      "solution": [
        "c0+",
        "c1+",
        "r1-",
        "r2-",
        "c3+",
        "c1-",
        "c0+"
      ]
    },
    {
      "id": "slip-10",
      "words": [
        "FISH",
        "CRAB",
        "WAVE",
        "SHIP"
      ],
      "alts": {
        "CRAB": [
          "CARB"
        ],
        "SHIP": [
          "HIPS"
        ]
      },
      "start": "AAEPWRSBCIIHVFSH",
      "par": 5,
      "solution": [
        "r0+",
        "r3-",
        "c0-",
        "r3-",
        "c2+"
      ]
    },
    {
      "id": "slip-11",
      "words": [
        "CAKE",
        "SOUP",
        "RICE",
        "BEAN"
      ],
      "alts": {
        "SOUP": [
          "OPUS"
        ],
        "BEAN": [
          "BANE"
        ]
      },
      "start": "PBAURECNEIAKSCOE",
      "par": 6,
      "solution": [
        "c1-",
        "r2-",
        "c0-",
        "c3-",
        "r3-",
        "c0+"
      ]
    },
    {
      "id": "slip-12",
      "words": [
        "BLUE",
        "PINK",
        "GRAY",
        "TEAL"
      ],
      "alts": {
        "TEAL": [
          "TALE",
          "LATE"
        ]
      },
      "start": "KPIEGRNABLALUTEY",
      "par": 7,
      "solution": [
        "c3+",
        "c3+",
        "r3+",
        "r3+",
        "r0-",
        "c2-",
        "r3+"
      ]
    },
    {
      "id": "slip-13",
      "words": [
        "BOOK",
        "PAGE",
        "READ",
        "TALE"
      ],
      "alts": {
        "PAGE": [
          "GAPE"
        ],
        "READ": [
          "DARE",
          "DEAR"
        ]
      },
      "start": "KBATREEEALGOPAOD",
      "par": 5,
      "solution": [
        "c0-",
        "c1-",
        "c3+",
        "r1+",
        "r3-"
      ]
    },
    {
      "id": "slip-14",
      "words": [
        "WARM",
        "COLD",
        "COOL",
        "HEAT"
      ],
      "alts": {
        "HEAT": [
          "HATE"
        ]
      },
      "start": "LAHOCERCWOAMODLT",
      "par": 6,
      "solution": [
        "c1+",
        "r0+",
        "c3-",
        "r0+",
        "r3+",
        "c0-"
      ]
    }
  ];
  return { PUZZLES };
});
