// Builds data.js. Each word set is scrambled with random slides, then solved exactly to find par.
// Usage: node make-puzzles.js          (writes data.js)
// Edit WORD_SETS to change the puzzles. Four 4-letter words per set, no repeats inside a set.
const fs = require('fs'), C = require('./core.js');
const WORD_SETS = [
  ['BEAR', 'ROAD', 'DEAL', 'LION'],
  ['PLAN', 'SNOW', 'TIME', 'DOOR'],
  ['RAIN', 'LAKE', 'WIND', 'SAND'],
  ['FIRE', 'STAR', 'BOAT', 'MILK'],
  ['COOK', 'BAKE', 'SALT', 'MEAL'],
  ['HOME', 'ROOF', 'WALL', 'DESK'],
  ['JUMP', 'RACE', 'SWIM', 'KICK'],
  ['GOLD', 'COIN', 'BANK', 'RICH'],
  ['TREE', 'LEAF', 'ROOT', 'SEED'],
  ['FISH', 'CRAB', 'WAVE', 'SHIP'],
  ['CAKE', 'SOUP', 'RICE', 'BEAN'],
  ['BLUE', 'PINK', 'GRAY', 'TEAL'],
  ['BOOK', 'PAGE', 'READ', 'TALE'],
  ['WARM', 'COLD', 'COOL', 'HEAT']
];
// Other real words that can be built from the same letters as a target. They count as correct too.
const ALTS = {
  BEAR: ['BARE'], DEAL: ['LEAD'], LION: ['LOIN'], SNOW: ['OWNS'], TIME: ['EMIT', 'ITEM', 'MITE'], DOOR: ['ODOR'],
  LAKE: ['KALE'], FIRE: ['RIFE'], STAR: ['ARTS', 'RATS', 'TARS', 'TSAR'], BAKE: ['BEAK'], SALT: ['LAST', 'SLAT'],
  MEAL: ['LAME', 'MALE'], RACE: ['ACRE', 'CARE'], COIN: ['ICON'], LEAF: ['FLEA'], CRAB: ['CARB'], SHIP: ['HIPS'],
  SOUP: ['OPUS'], BEAN: ['BANE'], TEAL: ['TALE', 'LATE'], PAGE: ['GAPE'], READ: ['DARE', 'DEAR'], HEAT: ['HATE']
};
const altsFor = words => Object.fromEntries(words.filter(w => ALTS[w]).map(w => [w, ALTS[w]]));
const MIN_PAR = 4, MAX_PAR = 7;
const puzzles = WORD_SETS.map((words, n) => {
  for (let seed = 1; seed < 5000; seed++) {
    const start = C.scramble(words, seed + n * 1000, 5 + (n % 3));
    const alts = altsFor(words);
    if (C.isSolved(start, words, alts) || C.rowMatches(start, words, alts).some(Boolean)) continue;
    const solution = C.minMoves(start, words, 9, alts);
    if (solution && solution.length >= MIN_PAR && solution.length <= MAX_PAR) {
      return { id: 'slip-' + String(n + 1).padStart(2, '0'), words, alts, start, par: solution.length, solution };
    }
  }
  throw new Error('No puzzle found for ' + words.join(' '));
});
const out = "(function (root, factory) {\n  if (typeof module === 'object' && module.exports) module.exports = factory();\n  else root.Data = factory();\n})(typeof self !== 'undefined' ? self : this, function () {\n" +
  "  // Generated by make-puzzles.js. 'start' is the scrambled grid, 'alts' are other words that count for a target,\n  // 'par' is the fewest possible moves and 'solution' is one shortest path.\n" +
  "  const PUZZLES = " + JSON.stringify(puzzles, null, 2).replace(/\n/g, '\n  ') + ";\n  return { PUZZLES };\n});\n";
fs.writeFileSync('data.js', out);
puzzles.forEach(p => console.log(p.id, p.words.join(' '), p.start.match(/.{4}/g).join('/'), 'par', p.par, p.solution.join(' ')));
